from .unet_shallow import UNet
from .unet_model import FullUNet
from .medium_unet import MediumUNet
from .unet_one_layer import OneLayerUNet
from .extra_deep_unet import ExtraDeepUNet
from .super_deep_unet import SuperDeepUNet
from .nnunet import nnUNet
from .resunet import ResUNet
from .extra_deep_unet_3d import ExtraDeep3DUNet
from .extra_deep_unet_3d_knee import ExtraDeepUNet3D_knee